### 부모 댓글을 생성할 경우

POST http://localhost:8080/comments
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjkwMTk2OTY5LCJleHAiOjE2OTM3OTY5Njl9.yahaEBvKBA7xelNuykx8TROhemnzJAsu1Sv5rrSfCM0

{
  "content": "댓글 내용",
  "eventId": "1",
  "parentId" : null
}

### 대댓글일 경우

POST http://localhost:8080/comments
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjkwMTk2OTY5LCJleHAiOjE2OTM3OTY5Njl9.yahaEBvKBA7xelNuykx8TROhemnzJAsu1Sv5rrSfCM0

{
  "content": "대댓글 내용",
  "eventId": "1",
  "parentId": "1"
}

### 행사에 포함되어 있는 댓글 조회

GET http://localhost:8080/comments?eventId=1
Content-Type: application/json

### 부모 ID로 대댓글 조회하기
GET http://localhost:8080/comments/1/children

### 댓글 삭제 /comments/{comment-id}

DELETE http://localhost:8080/comments/2
Authorization: bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjkwMTk2OTY5LCJleHAiOjE2OTM3OTY5Njl9.yahaEBvKBA7xelNuykx8TROhemnzJAsu1Sv5rrSfCM0

### 댓글 수정 /comments/{comment-id}

PATCH http://localhost:8080/comments/1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjkwMTk2OTY5LCJleHAiOjE2OTM3OTY5Njl9.yahaEBvKBA7xelNuykx8TROhemnzJAsu1Sv5rrSfCM0

{
  "content": "변경될 내용"
}
