### Event 상세조회
GET http://localhost:8080/events/1

### Event 참여자 목록에 멤버 추가
POST http://localhost:8080/events/1/participants
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjkwMTk2OTY5LCJleHAiOjE2OTM3OTY5Njl9.yahaEBvKBA7xelNuykx8TROhemnzJAsu1Sv5rrSfCM0

{
  "memberId": 1
}
