### 필터링 없이 특정 연도 & 월의 행사 목록 조회

GET http://localhost:8080/events?year=2023&month=7
Content-Type: application/json

### 상태 필터링이 적용된 경우

GET http://localhost:8080/events?year=2023&month=7&status=진행 중
Content-Type: application/json

### 태그 필터링이 적용된 경우

GET http://localhost:8080/events?year=2023&month=7&tag=안드로이드
Content-Type: application/json

### 태그 필터링과 상태 필터링이 모두 적용된 경우

GET http://localhost:8080/events?year=2023&month=7&tag=백엔드&status=진행 중
Content-Type: application/json

### Event 상세조회
GET http://localhost:8080/events/1

### Event 참여자 목록에 멤버 추가
POST http://localhost:8080/events/1/participants
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjkwMTk2OTY5LCJleHAiOjE2OTM3OTY5Njl9.yahaEBvKBA7xelNuykx8TROhemnzJAsu1Sv5rrSfCM0

{
  "memberId": 1
}

### Event 참여자 목록에서 멤버 삭제
DELETE http://localhost:8080/events/1/participants
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjkwMTk2OTY5LCJleHAiOjE2OTM3OTY5Njl9.yahaEBvKBA7xelNuykx8TROhemnzJAsu1Sv5rrSfCM0

{
  "memberId": 1
}

### 행사 참여자 목록 조회
GET http://localhost:8080/events/1/participants
