### 사용자 초기 Activity 및 이름 저장

POST http://localhost:8080/members
Content-Type: application/json

{
  "name": "우르",
  "activitieIds": [
    1,
    2
  ]
}

### 사용자 Activity 추가
POST http://localhost:8080/members/activities
Content-Type: application/json

{
  "activitieIds": [
    4,
    5,
    6
  ]
}

### 사용자 Activity 제거
DELETE http://localhost:8080/members/activities
Content-Type: application/json

{
  "activitieIds": [
    1,
    2
  ]
}

### 사용자의 오픈 프로필 URL 업데이트
PUT http://localhost:8080/members/open-profile-url
Content-Type: application/json

{
  "openProfileUrl": "https://open.kakao.com/profile"
}
