### 알림 저장

POST http://localhost:8080/notifications
Content-Type: application/json

{
  "senderId" : 1,
  "receiverId" : 3,
  "message" : "테스트 알람이다",
  "eventId" : 1
}

### FCM 토큰 저장 API (새롭게 저장)

POST http://localhost:8080/notifications/token
Content-Type: application/json

{
  "token" : "토큰이다",
  "memberId" : 1
}

### FCM 토큰 저장 API (기존에 있던 것 수정)

POST http://localhost:8080/notifications/token
Content-Type: application/json

{
  "token" : "수정된 토큰이다",
  "memberId" : 1
}

### 알림 상태를 변경하는 API

PATCH http://localhost:8080/notifications/2
Content-Type: application/json

{
  "updatedStatus" : "ACCEPTED"
}

### id로 알림 조회하는 API

GET http://localhost:8080/notifications/1
