name: Kerdy Android CI

on:
  push:
    branches: [ "android-main" ]
  pull_request:
    branches: [ "android-main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Gradle 빌드
      run: ./gradlew build
    - name: 테스트 코드 실행
      run: ./gradlew check
    - name: 코틀린 Lint 체크
      run: ./gradlew ktlintCheck
    - name: 완료 문구
      run: echo "CI를 완료하였습니다!"
      
