name: Kerdy Backend Build Test

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - backend-main

jobs:
  build:
    name: Build with Gradle
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0.28
        env:
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: 1234
          MYSQL_DATABASE: kerdy
        ports:
          - 13306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: backend-main

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: cd backend directory
        run: cd backend/emm-sale

      - name: Give permission for Gradle
        run: chmod +x gradlew

      - name: Build with Gradle
        run: gradlew clean build
